// <auto-generated />
using System;
using MA_Delivery_Project.DBConnStr;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MA_Delivery_Project.LabehData.Info
{
    [DbContext(typeof(LabehDbConext))]
    [Migration("20221020123052_001")]
    partial class _001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MA_Delivery_Project.Models.Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AnswerTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("AnswerTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Branch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrgsSubID")
                        .HasColumnType("int");

                    b.Property<string>("latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("longtitude")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrgsSubID");

                    b.ToTable("BranchTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.BranchSubOrgsContract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("ContractID")
                        .HasColumnType("int");

                    b.Property<decimal>("GenerationFees")
                        .HasColumnType("decimal(13,2)");

                    b.Property<int>("OrgsSubID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.HasIndex("ContractID");

                    b.HasIndex("OrgsSubID");

                    b.ToTable("BranchSubOrgsContractTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Commision", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<decimal>("Commisionamount")
                        .HasColumnType("decimal(13,2)");

                    b.Property<int>("ContactID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentWayID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ContactID");

                    b.HasIndex("PaymentWayID");

                    b.ToTable("CommisionTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Contract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(13,2)");

                    b.Property<string>("DateFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrgsSubIdRef")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrgsSubIdRef");

                    b.ToTable("ContractTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.ContractCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ConractCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContractCategoryTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.ContractCCat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ContactCatID")
                        .HasColumnType("int");

                    b.Property<int>("ContractID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ContactCatID");

                    b.HasIndex("ContractID");

                    b.ToTable("ContractCCatTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CustomerCode")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatitudeDefault")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongtitudeDefault")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CustomerTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.CustomerCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CategoyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CustomerCategoryTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.CustomerCusCat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CurrentDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerCatID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerCatID");

                    b.HasIndex("CustomerID");

                    b.ToTable("CustomerCusCatTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Driver", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DriverCode")
                        .HasColumnType("int");

                    b.Property<int>("DriverCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("DriverEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DriverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("DriverTypeId")
                        .HasColumnType("int");

                    b.Property<string>("LatitudeDefault")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LongtitudeDefault")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("DriverCompanyId");

                    b.HasIndex("DriverTypeId");

                    b.ToTable("DriverTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriverCompany", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverCompCatID")
                        .HasColumnType("int");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DriverCompCatID");

                    b.ToTable("DriverCompanyTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriverCompContract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("DateFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DateTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("DriverCompID")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("DriverCompID");

                    b.ToTable("DriverCompContractTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriversCompaniesCat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("CompaniesType")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("DriversCompaniesCatTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriversContract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("ContractDetaill")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DateFrom")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DateTo")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("DriverId");

                    b.ToTable("DriversContractTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriverTracking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CurentDTime")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CurrentHour")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("DriverCode")
                        .HasColumnType("int");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Longtitude")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("DriverID");

                    b.ToTable("DriverTrackingTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriverTrackingOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("DriverTrackingId")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Longtitude")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DriverTrackingId");

                    b.HasIndex("OrderId");

                    b.ToTable("DriverTrackingOrderTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriverVehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<string>("UsingDate")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DriverID");

                    b.HasIndex("VehicleID");

                    b.ToTable("DriverVehicleTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.EvaluateAnswer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("EvaluateAnswerTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.EvaluateDriver", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("EvaluateDriverTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.GeneralWalet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("BalanceValue")
                        .HasColumnType("decimal(13,2)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("FlagID")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserID");

                    b.ToTable("GeneralWaletTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BranchesIDRef")
                        .HasColumnType("int");

                    b.Property<int>("FlagType")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemCost")
                        .HasColumnType("decimal(13,2)");

                    b.Property<int>("ItemsCode")
                        .HasColumnType("int");

                    b.Property<string>("ItemsName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("OrgsSubRef")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BranchesIDRef");

                    b.HasIndex("OrgsSubRef");

                    b.ToTable("ItemTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.ItemOrderOffer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("FlagOfferItem")
                        .HasColumnType("int");

                    b.Property<int>("ItemIDRef")
                        .HasColumnType("int");

                    b.Property<int>("OfferIDRef")
                        .HasColumnType("int");

                    b.Property<int>("OrderIDRef")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ItemIDRef");

                    b.HasIndex("OfferIDRef");

                    b.HasIndex("OrderIDRef");

                    b.ToTable("ItemOrderOfferTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.LatLongArrived", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LongTitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("OrderRef")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderRef");

                    b.ToTable("LatLongArrivedTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.MainOrgContact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BranchesContact")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("OrgsSubbIDRef")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("BranchesContact");

                    b.HasIndex("OrgsSubbIDRef");

                    b.ToTable("MainOrgContactTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Offer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BranchesIDRef")
                        .HasColumnType("int");

                    b.Property<int>("OffersCode")
                        .HasColumnType("int");

                    b.Property<string>("OffersDetails")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<decimal>("OffersPrice")
                        .HasColumnType("decimal(13,2)");

                    b.HasKey("ID");

                    b.HasIndex("BranchesIDRef");

                    b.ToTable("OfferTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.OfferItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ItemIDef")
                        .HasColumnType("int");

                    b.Property<int>("OfferIDRef")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ItemIDef");

                    b.HasIndex("OfferIDRef");

                    b.ToTable("OfferItemTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("CurrentDate")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CustomerID");

                    b.ToTable("OrderTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Organization", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("OrganizeCode")
                        .HasColumnType("int");

                    b.Property<string>("OrganizeName")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("OrganizationTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.OrgsSub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Latitiude")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Logtitude")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("OrganizationRef")
                        .HasColumnType("int");

                    b.Property<int>("OrgsSubCode")
                        .HasColumnType("int");

                    b.Property<string>("OrgsSubName")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("OrganizationRef");

                    b.ToTable("OrgsSubTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Payment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("PaymentWay")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("PaymentTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Staff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("StaffTypeID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("StaffTypeID");

                    b.ToTable("StaffTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.StaffType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("StaffTypeTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("FlagVal")
                        .HasColumnType("int");

                    b.Property<int>("IDRef")
                        .HasColumnType("int");

                    b.Property<int>("StockCode")
                        .HasColumnType("int");

                    b.Property<string>("StockDetails")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("IDRef");

                    b.ToTable("StockTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.SubCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationRef")
                        .HasColumnType("int");

                    b.Property<string>("SubCatName")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.HasIndex("OrganizationRef");

                    b.ToTable("SubCategoryTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.SubCategoryOrgsSub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("OrgSubIDRef")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrgSubIDRef");

                    b.HasIndex("SubCategoryID");

                    b.ToTable("SubCategoryOrgsSubTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("VehicleName")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("VehicleTab", "LabehDB");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Answer", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.EvaluateAnswer", "evaluateAnswer")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evaluateAnswer");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Branch", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.OrgsSub", "orgsSub")
                        .WithMany()
                        .HasForeignKey("OrgsSubID");

                    b.Navigation("orgsSub");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.BranchSubOrgsContract", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Contract", "Contracts")
                        .WithMany()
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.OrgsSub", "OrgsSub")
                        .WithMany()
                        .HasForeignKey("OrgsSubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Contracts");

                    b.Navigation("OrgsSub");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Commision", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Contract", "contract")
                        .WithMany()
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Payment", "payment")
                        .WithMany()
                        .HasForeignKey("PaymentWayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("contract");

                    b.Navigation("payment");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Contract", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.OrgsSub", "orgsub")
                        .WithMany()
                        .HasForeignKey("OrgsSubIdRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("orgsub");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.ContractCCat", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.ContractCategory", "ContCat")
                        .WithMany()
                        .HasForeignKey("ContactCatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Contract", "Contracts")
                        .WithMany()
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContCat");

                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.CustomerCusCat", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.CustomerCategory", "CusCat")
                        .WithMany()
                        .HasForeignKey("CustomerCatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Customer", "Cus")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cus");

                    b.Navigation("CusCat");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Driver", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.DriverCompany", "DriverCompany")
                        .WithMany()
                        .HasForeignKey("DriverCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.DriversCompaniesCat", "DriversCompaniesCat")
                        .WithMany()
                        .HasForeignKey("DriverTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverCompany");

                    b.Navigation("DriversCompaniesCat");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriverCompany", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.DriversCompaniesCat", "DriversCompaniesCats")
                        .WithMany()
                        .HasForeignKey("DriverCompCatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriversCompaniesCats");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriverCompContract", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.DriverCompany", "DriverCompany")
                        .WithMany()
                        .HasForeignKey("DriverCompID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverCompany");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriversContract", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Driver", "drivers")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("drivers");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriverTracking", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Driver", "Drivers")
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriverTrackingOrder", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.DriverTracking", "DriverTracking")
                        .WithMany()
                        .HasForeignKey("DriverTrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverTracking");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.DriverVehicle", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Driver", "Drivers")
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Vehicle", "Vehicles")
                        .WithMany()
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drivers");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.GeneralWalet", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Driver", "Drivers")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drivers");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Item", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Branch", "Branches")
                        .WithMany()
                        .HasForeignKey("BranchesIDRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.OrgsSub", "OrgsSub")
                        .WithMany()
                        .HasForeignKey("OrgsSubRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branches");

                    b.Navigation("OrgsSub");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.ItemOrderOffer", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Item", "Items")
                        .WithMany()
                        .HasForeignKey("ItemIDRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Offer", "Offers")
                        .WithMany()
                        .HasForeignKey("OfferIDRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderIDRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Items");

                    b.Navigation("Offers");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.LatLongArrived", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.MainOrgContact", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Branch", "Branches")
                        .WithMany()
                        .HasForeignKey("BranchesContact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.OrgsSub", "OrgsSub")
                        .WithMany()
                        .HasForeignKey("OrgsSubbIDRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branches");

                    b.Navigation("OrgsSub");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Offer", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Branch", "Branches")
                        .WithMany()
                        .HasForeignKey("BranchesIDRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branches");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.OfferItem", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Item", "Items")
                        .WithMany()
                        .HasForeignKey("ItemIDef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Offer", "Offers")
                        .WithMany()
                        .HasForeignKey("OfferIDRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Items");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Order", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Branch", "Branches")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.Customer", "Customers")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branches");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.OrgsSub", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Organization", "Organizations")
                        .WithMany()
                        .HasForeignKey("OrganizationRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Staff", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.StaffType", "StaffType")
                        .WithMany()
                        .HasForeignKey("StaffTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffType");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.Stock", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Item", "Items")
                        .WithMany()
                        .HasForeignKey("IDRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.SubCategory", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.Organization", "Organizations")
                        .WithMany()
                        .HasForeignKey("OrganizationRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("MA_Delivery_Project.Models.SubCategoryOrgsSub", b =>
                {
                    b.HasOne("MA_Delivery_Project.Models.OrgsSub", "OrgsSub")
                        .WithMany()
                        .HasForeignKey("OrgSubIDRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MA_Delivery_Project.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrgsSub");

                    b.Navigation("SubCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
